### ISSUE TITLE
Suggestion: Config option for boss/miniboss announcements

### ISSUE THREAD

**Issue by Cephelo** [Unknowneth/Mob-AI-Tweaks#10]
A config option for whether chat announcements are shown would be excellent, since I know not everyone may want them.

**Comment by Unknowneth** [comment]
will do

**Comment by Niconoko** [comment]
Could ye add an option to disable boss bar for mini boss too? (´・ω・｀)

**Comment by Unknowneth** [comment]
sure

**Comment by Unknowneth** [comment]
both implemented as of 1.3.6, will not close issue just yet until this also releases for 1.20

**Comment by NeuTraLZero** [comment]
Any update on this?

**Comment by Unknowneth** [comment]
update released, sorry for delays
