### ISSUE TITLE
[Possible Bug]: Server Crashing from Ticking entity after a while

### ISSUE THREAD

**Issue by Mysticpasta1** [Unknowneth/Mob-AI-Tweaks#11]
server is crashing from the livingAttackEvent by random mobs like skeletons, best to check your code to see if ticking entities are possible. Skeleton entity and a lightning bolt were both ticking

**Comment by Unknowneth** [comment]
gonna need to test this

**Comment by Mysticpasta1** [comment]
It might have been the more curse mod too, with apotheosis. This might have not been a cause of it

**Comment by suerion** [comment]
> It might have been the more curse mod too, with apotheosis. This might have not been a cause of it

@Mysticpasta1 did you have other mods or an latest.log for crash?

**Comment by Mysticpasta1** [comment]
I think it was the more curse mod
I will be checking your mod again :D

**Comment by Mysticpasta1** [comment]
your mod is fine
