### ISSUE TITLE
[Crash] Incompatibility with mod

### ISSUE THREAD

**Issue by tehehe22** [Unknowneth/Mob-AI-Tweaks#13]
There seems to be a incompatibility with the mod "Mob Variants" by Xires87 which makes the game crash anytime you load up a save or spawn a undead warrior (a skeleton that uses a stone sword)

**Comment by Unknowneth** [comment]
I see, I have seen comments reporting the same issue but never specified which "mob variants" mod is it (there are a lot of mods with that name)
Will check what causes it

**Comment by shallow-zzt** [comment]
Maybe it refers the mod https://modrinth.com/mod/fryc-mob-variants

**Comment by Unknowneth** [comment]
I have great news: found the conflict and was able to fix it! this should be fixed next update

**Comment by Unknowneth** [comment]
fixed as of 1.3.6 for 1.20 and 1.3.7 as of 1.21
