### ISSUE TITLE
[1.3.6] setting "creeper_explosions_rework" to false prevents creepers from exploding altogether

### ISSUE THREAD

**Issue by BIoxyest** [Unknowneth/Mob-AI-Tweaks#15]
I wanted to disable the creeper's fuse timer getting interrupted by attacking because I thought it made creepers less intimidating, but disabling this setting causes them to stop exploding altogether.
https://github.com/user-attachments/assets/49d8420a-db34-433f-8ace-31cd531da7d0

**Comment by Unknowneth** [comment]
Ok, I just recently found out why this is happening

No clue when update will release cause I'm very busy rn

**Comment by Unknowneth** [comment]
fixed as of 1.3.6 for 1.20 and 1.3.7 as of 1.21
