### ISSUE TITLE
Wither skeletons no attack cooldown

### ISSUE THREAD

**Issue by vividlyflares** [Unknowneth/Mob-AI-Tweaks#18]
hello! is it normal for wither skeleton's melee attacks to have no cooldown? in comparison to zombies, their attacks have intervals, they are not continuous spammed attacks. but with mob ai tweaked wither skeletons, their melee attacks seems to have no cooldown whatsoever, as if it is a player spamming left click. 
thanks!

**Comment by Unknowneth** [comment]
do you have "Crazy Mobs Mode" gamerule enabled? If so, this is normal, if not, then I will fix this.

**Comment by Unknowneth** [comment]
should be fixed for 1.21, 1.20 should come in a day or two

**Comment by Unknowneth** [comment]
should be fixed now as of version 1.4.0 for both 1.20 and 1.21
