### ISSUE TITLE
Suggestion: Add Compatibility with Dungeons and Taverns

### ISSUE THREAD

**Issue by BM123789** [Unknowneth/Mob-AI-Tweaks#19]
I really like what this mod does to change phantoms. It's just that this doesn't really work well with Dungeons and Taverns which has a phantom boss and phantom enemies in one of its dungeons. Maybe you could disable the phantom rework for phantoms that spawn from trial spawners?

**Comment by Unknowneth** [comment]
Sure thing

**Comment by Unknowneth** [comment]
added as of 1.4.1 for both 1.20 and 1.21
