### ISSUE TITLE
Suggestion: Disable the new skeleton strafing AI/speed in config

### ISSUE THREAD

**Issue by TheBiggestHuman** [Unknowneth/Mob-AI-Tweaks#20]
This mod is really wonderful and customizable! I love the new AI changes and tweaks.

The only issue I have with it is the speed of the skeletons when strafing.
Is it possible to add a config option to disable the new speed of strafing and return the original function? Or just an option to make skeletons as slow as they were before?

Thank you!

**Comment by Unknowneth** [comment]
in all honesty, I forgot to add this

I'll close the issue once its added

**Comment by Unknowneth** [comment]
Added as of 1.5.0
