### ISSUE TITLE
Cant start fabric server [Fabric 1.20]

### ISSUE THREAD

**Issue by pewblaze** [Unknowneth/Mob-AI-Tweaks#4]
Hi, i downloaded the mod today & tried to start my server with it - but it crashes with this error:
`Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for mob-ai-tweaks.mixins.json:WitherEntityMixin from mod mob-ai-tweaks during activity: [Transform -> Method onSpawned(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> INVOKESTATIC -> net/minecraft/class_310::method_1551:()Lnet/minecraft/class_310;]
`
I can start the Clientside without problems. 

latest.log:
https://gist.github.com/pewblaze/3355179db865a386fd076aea2b15ea3f

**Comment by Unknowneth** [comment]
should be fixed as of 1.3.1-1.20
feel free to close the issue if it is actually fixed

**Comment by pewblaze** [comment]
Yes it works now, thanks! :)
