### ISSUE TITLE
[Bug] Mobs cannot jump onto one block high.

### ISSUE THREAD

**Issue by lzm11111111** [Unknowneth/Mob-AI-Tweaks#5]
Self explanatory, when I installed this mod, the mobs are unable to jump onto one block high, I only installed two mods (fabric api and this mod, version is 1.20.1)

https://github.com/user-attachments/assets/e774be3d-b893-42d1-a263-2068764ccf51

https://github.com/user-attachments/assets/d3c9a638-150c-415d-b212-0055a9ef1156

**Comment by Unknowneth** [comment]
should be fixed by 1.3.2-1.20
feel free to close if it is truly fixed
(also dev note, this bug existed since release, I just never noticed it because the conditions for it to happen are oddly specific)
