### ISSUE TITLE
Woodland Mansion Illagers cause the server side to crash and freeze

### ISSUE THREAD

**Issue by Mysticpasta1** [Unknowneth/Mob-AI-Tweaks#6]
used modernfix stacktrace to find it out plus a binary  search to track the mod causing it

**Comment by Mysticpasta1** [comment]
to reproduce go near a woodland mansion in single player and watch the server die

**Comment by Unknowneth** [comment]
found the issue, its just the duplicate UUID error

**Comment by Unknowneth** [comment]
should be fixed as of 1.3.4 for 1.21 (1.20 fix in a bit)

**Comment by Mysticpasta1** [comment]
did you ever fix #3

**Comment by Unknowneth** [comment]
still have not figured it out, forge keeps crashing on me even with just sinytra

**Comment by Mysticpasta1** [comment]
Can you add me on discord I'm HauntedPasta1

**Comment by Mysticpasta1** [comment]
I know how to fix it I need the 1.20.1 code first (the one that is upload to github is the 1.21 code src.zip

**Comment by Mysticpasta1** [comment]
https://discord.com

**Comment by Mysticpasta1** [comment]
try this user name if the above didn't work

hauntedpasta1
