### ISSUE TITLE
want to fix issue #3 do you have discord

### ISSUE THREAD

**Issue by Mysticpasta1** [Unknowneth/Mob-AI-Tweaks#7]
my username is hauntedpasta1

**Comment by Unknowneth** [comment]
holup, lemme see if i remember my log in

**Comment by Mysticpasta1** [comment]
were you able to remember it?

**Comment by Unknowneth** [comment]
i cannot find your username

**Comment by Mysticpasta1** [comment]
try MysticPasta1 that is my display name

**Comment by Mysticpasta1** [comment]
if you can't find me tell me your discord username and displayname and I will try to find you

**Comment by Unknowneth** [comment]
none, try messaging me instead
notunanancyowen#2661
